### ISSUE TITLE
IP doesn't change - Chromewebdriver proxy

### ISSUE THREAD

**Issue by jcardonne** [Smartproxy/Selenium#2]
.

**Comment by SnnK** [comment]
I am having the same problem.

2 people from live chat could not solve the problem. The support team created a ticket. I'm waiting for an answer.

**Comment by TrgtDmr** [comment]
It definitely doesn't work. I talked to 3 people from live support, they directed them to the technical team twice, but the problem did not change. Absolutely stay away.
